Renommage en MaFamilleIci
entrepreneur-interet-general/design-system pull request #8
Opened 2019-08-14 16:09 UTC by milkosofi

2019-08-14 16:36 UTC, milkosofi commented
Salut @jbledevehat ! Actuellement, les logos des défis sont identifiés par des numéros. J'ai commencé à les renommer pour qu'il soit plus facile de s'y retrouver. J'imagine qu'il y a des liens avec d'autres pages (notamment les pages de présentation des défis), je vais donc voir avec @AntoineAugusti s'il y a une manière simple de gérer ces liens. 

J'aimerais également renommer le dossier qui contient les logos DIG : actuellement il s'intitule LogoEIG4 et j'aimerais qu'il s'intitule logos-dig. Encore une fois, j'imagine qu'un renommage aura des répercussions, mais je veux bien en discuter.

2019-08-19 08:15 UTC, AntoineAugusti commented
Il y aura effectivement besoin de changer des noms de logos dans le site EIG et Ma Semaine DIG mais les fichiers utilisés sont copiés et non pris à la source pour le moment.

Ainsi, la PR peut être mergée.

2019-08-19 08:16 UTC, AntoineAugusti requested changes
Pas besoin de garder les numéros dans les noms de fichiers. Je pense que seul le nom du défi suffit

2019-08-19 08:21 UTC, jbledevehat commented
@milkosofi par convention, il faut éviter des mettre des points "." dans le nom d'un fichier. 
Le "point" est que pour donner l’extension du fichier (.png ou .svg). Après les autres fichiers on pour convention de mettre tout attaché commençant par une majuscule devant chaque mot (ex : SocialConnect.png)

2019-08-19 08:45 UTC, merged

2019-08-19 10:14 UTC, AntoineAugusti commented
Mapping des anciens noms / nouveaux noms :

02.png → Alphabet.png
04.png → RembourSante.png
05.png → ProxiRH.png
10.png → PlaniPref.png
12.png → INPN-Espaces.png
13.png → ResorptionBidonvilles.png
14.png → Recrues.png
16.png → VigicrUX.png
17.png → MaFamilleIci.png